export const CURRICULUM = [
  // todo: add combo with space for every level
  { id: 1, keys: ['f', 'j'], name: 'Home Row: F, J' },
  { id: 2, keys: ['f', 'j', ' '], name: 'Home Row: F, J, Space' },
  { id: 3, keys: ['d', 'k'], name: 'Home Row: D, K' },
  { id: 4, keys: ['d', 'k', ' '], name: 'Home Row: D, K, Space' },
  { id: 5, keys: ['s', 'l'], name: 'Home Row: S, L' },
  { id: 6, keys: ['s', 'l', ' '], name: 'Home Row: S, L, Space' },
  { id: 7, keys: ['a', 'g', 'h', ';'], name: 'Home Row: A, G, H, ;' },
  { id: 8, keys: ['a', 'g', 'h', ';', ' '], name: 'Home Row: A, G, H, ;, Space' },
  { id: 9, keys: ['a', 'd', 's', 'f', 'g', 'h', ';', 'l', 'k', 'j'], name: 'Home Row: Home Row Full' },
  { id: 9, keys: ['a', 'd', 's', 'f', 'g', 'h', ';', 'l', 'k', 'j', ' '], name: 'Home Row: Home Row Full, Space' },
  { id: 10, keys: ['r', 'u'], name: 'Top Row: R, U' },
  { id: 11, keys: ['r', 'u', ' '], name: 'Top Row: R, U, Space' },
  { id: 12, keys: ['t', 'y'], name: 'Top Row: T, Y' },
  { id: 13, keys: ['t', 'y', ' '], name: 'Top Row: T, Y, Space' },
  { id: 14, keys: ['e', 'i'], name: 'Top Row: E, I' },
  { id: 15, keys: ['e', 'i', ' '], name: 'Top Row: E, I, Space' },
  { id: 16, keys: ['w', 'o'], name: 'Top Row: W, O' },
  { id: 17, keys: ['w', 'o', ' '], name: 'Top Row: W, O, Space' },
  { id: 18, keys: ['q', 'p'], name: 'Top Row: Q, P' },
  { id: 19, keys: ['q', 'p', ' '], name: 'Top Row: Q, P, Space' },
  { id: 20, keys: ['r', 'u', 't', 'y', 'e', 'i', 'w', 'o', 'q', 'p'], name: 'Top Row: Top Row Full' },
  { id: 21, keys: ['r', 'u', 't', 'y', 'e', 'i', 'w', 'o', 'q', 'p', ' '], name: 'Top Row: Top Row Full, Space' },
  { id: 22, keys: ['v', 'n'], name: 'Bottom Row: V, N'},
  { id: 23, keys: ['v', 'n', ' '], name: 'Bottom Row: V, N, Space'},
  { id: 24, keys: ['b', 'm'], name: 'Bottom Row: B, M'},
  { id: 25, keys: ['b', 'm', ' '], name: 'Bottom Row: B, M, Space'},
  { id: 26, keys: ['c', ','], name: 'Bottom Row: C, ,'},
  { id: 27, keys: ['c', ',', ' '], name: 'Bottom Row: C, ,, Space'},
  { id: 28, keys: ['x', '.'], name: 'Bottom Row: X, .' },
  { id: 29, keys: ['x', '.', ' '], name: 'Bottom Row: X, ., Space' },
  { id: 30, keys: ['z', '/'], name: 'Bottom Row: Z, /'},
  { id: 31, keys: ['z', '/', ' '], name: 'Bottom Row: Z, /, Space' },
  { id: 32, keys: ['v', 'n', 'b', 'm', 'c', ',', 'x', '.', 'z', '/'], name: 'Bottom Row: Bottom Row Full' },
  { id: 33, keys: ['v', 'n', 'b', 'm', 'c', ',', 'x', '.', 'z', '/', ' '], name: 'Bottom Row: Bottom Row Full, Space' },
  { id: 34, keys: ['q','w','e','r','t','h','j','k','l',';'], name: 'Top-Home Combo: Left Top, Right Home'},
  { id: 35, keys: ['q','w','e','r','t','h','j','k','l',';',' '], name: 'Top-Home Combo: Left Top, Right Home, Space'},
  { id: 36, keys: ['a','s','d','f','g','y','u','i','o','p'], name: 'Top-Home Combo: Left Home, Right Top'},
  { id: 37, keys: ['a','s','d','f','g','y','u','i','o','p',' '], name: 'Top-Home Combo: Left Home, Right Top, Space'},
  { id: 38, keys: ['q','w','e','r','t','y','u','i','o','p','a','s','d','f','g','h','j','k','l',';'], name: 'Top-Home Combo: All Keys Top and Home'},
  { id: 39, keys: ['q','w','e','r','t','y','u','i','o','p','a','s','d','f','g','h','j','k','l',';',' '], name: 'Top-Home Combo: All Keys Top and Home, Space'},
  { id: 40, keys: ['z','x','c','v','b','h','j','k','l',';'], name: 'Bottom-Home Combo: Left Bottom, Right Home'},
  { id: 41, keys: ['z','x','c','v','b','h','j','k','l',';',' '], name: 'Bottom-Home Combo: Left Bottom, Right Home, Space'},
  { id: 42, keys: ['a','s','d','f','g','n','m',',','.'], name: 'Bottom-Home Combo: Left Home, Right Bottom'},
  { id: 43, keys: ['a','s','d','f','g','n','m',',','.',' '], name: 'Bottom-Home Combo: Left Home, Right Bottom, Space'},
  { id: 44, keys: ['a','s','d','f','g','h','j','k','l',';','z','x','c','v','b','n','m',',','.','/'], name: 'Bottom-Home Combo: All Keys Bottom and Home'},
  { id: 45, keys: ['a','s','d','f','g','h','j','k','l',';','z','x','c','v','b','n','m',',','.','/',' '], name: 'Bottom-Home Combo: All Keys Bottom and Home, Space'},
  { id: 46, keys: ['z','x','c','v','b','y','u','i','o','p'], name: 'Top-Bottom Combo: Left Bottom, Right Top'},
  { id: 47, keys: ['z','x','c','v','b','y','u','i','o','p',' '], name: 'Top-Bottom Combo: Left Bottom, Right Top, Space'},
  { id: 48, keys: ['q','w','e','r','t','n','m',',','.','/'], name: 'Top-Bottom Combo: Left Top, Right Bottom'},
  { id: 49, keys: ['q','w','e','r','t','n','m',',','.','/',' '], name: 'Top-Bottom Combo: Left Top, Right Bottom, Space'},
  { id: 50, keys: ['q','w','e','r','t','y','u','i','o','p','z','x','c','v','b','n','m',',','.','/'], name: 'All Rows: All Keys Top, Home and Bottom'},
  { id: 51, keys: ['q','w','e','r','t','y','u','i','o','p','z','x','c','v','b','n','m',',','.','/',' '], name: 'All Rows: All Keys Top, Home and Bottom, Space'}
];

export const generateSequence = (keys, length = 10) => {
  return Array.from({ length }, () => keys[Math.floor(Math.random() * keys.length)]);
};
