export const EN_SENTENCES = [
  "The K-pop idols danced while fighting shadow demons.",
  "We need more Robux to buy that awesome limited accessory.",
  "Colt used his super attack to break the wall in Brawl Stars.",
  "She sang a high note that banished the monster forever.",
  "I traded my frost dragon for a mega neon unicorn in Adopt Me.",
  "Spike threw a cactus grenade right into the bushes.",
  "The demon hunters glowed with magic light on the stage.",
  "Building a massive obby in Roblox takes a lot of testing.",
  "Shelly hid in the tall grass waiting to ambush the enemy team.",
  "Their new music video was actually a secret battle against vampires.",
  "My avatar looks so cool with the new limited items!",
  "El Primo jumped high into the air with ten purple gems.",
  "The lead singer dodged a fireball while hitting a perfect high note.",
  "My neon fly ride shadow dragon is the rarest pet in the server!",
  "Bull charged through the bushes and caught the enemy team by surprise.",
  "With a flash of pink light, the monsters were trapped in a magical bubble.",
  "Can you help me beat this impossible tower of hell level?",
  "Crow threw poisonous daggers to stop the gem carrier from escaping.",
  "During the dance break, their lightsticks turned into glowing weapons.",
  "We spent hours building our dream house in Bloxburg.",
  "Piper sniped from across the map and saved the day at the last second.",
  "The music faded out as the ultimate shadow beast appeared on stage.",
  "Getting a legendary Starr Drop gave me an awesome new skin!",
  "Make sure you don't step on the red lava blocks in the obby.",
  "The crowd cheered as the idol slashed through the phantom army.",
  "Playing hide and seek in Murder Mystery is always so stressful!",
  "Leon used his smoke bomb invisibility to sneak past the enemy team.",
  "The concert ended with fireworks that completely destroyed the dark portal.",
  "I just hatched a mythical egg and got something totally amazing!",
  "Dynamike threw a huge explosive barrel right onto the safe.",
  "We need to unlock all the doors before Piggy catches us.",
  "The bass drop sent a shockwave that cleared out all the lesser demons.",
  "Mortis dashed forward with his shovel to grab the final power cube.",
  "Welcome to my tycoon where we build the biggest candy factory ever!",
  "The rapper's verse was so fast it shattered the icy demon's armor.",
  "They synchronized their teleportation spells to match the beat of the song.",
  "The fans' cheers charged up the group's ultimate lightstick attack.",
  "She deflected the shadow arrows using a shield made of pure soundwaves.",
  "The backup dancers were actually elite monster hunters in disguise.",
  "A massive phantom tried to crash the fan meeting, but the idols handled it.",
  "Their comeback stage featured a real magical duel against a vampire lord.",
  "He spun his microphone stand like a staff to sweep away the goblins.",
  "The glowing stage outfits were woven with special anti-magic threads.",
  "When they harmonize, a protective barrier surrounds the entire stadium.",
  "The album's secret track was actually an incantation to seal the portal.",
  "I finally bought the gamepass that lets me run super fast in Brookhaven.",
  "We had to hack the computers and escape before the beast caught us in Flee the Facility.",
  "My dream is to get the Headless Horseman head during the Halloween event.",
  "The trading plaza in Pet Simulator 99 is always packed with players.",
  "I managed to survive the tsunami round in Natural Disaster Survival.",
  "You have to click as fast as you can to build your stats in Ninja Legends.",
  "The new BedWars update added an overpowered sword to the item shop.",
  "Can you spawn a vehicle for me in Jailbreak so we can rob the bank?",
  "I customized my stand in Pls Donate and earned hundreds of Robux.",
  "Don't look at the slenderman or your screen will start turning completely static!",
  "Building a secret underground bunker in Bloxburg cost me a fortune.",
  "Bo planted explosive mines perfectly around the gem mine to protect it.",
  "Surge upgraded himself to max level and started dodging every single shot.",
  "Tick's head detached and chased the enemy brawler all the way into the poison gas.",
  "Amber sprayed a trail of fire fluid and ignited the entire middle of the map.",
  "You have to watch out for sneaky Cordelius pulling you into the Shadow Realm!",
  "Gene used his magical hand super to pull the enemy gem carrier through the wall.",
  "Buzz used his torpedo buoy to grapple onto the wall and escape danger.",
  "Getting a team wipe with a perfectly timed Tara black hole is extremely satisfying.",
  "Penny placed her mortar behind a wall where nobody could easily destroy it.",
  "Using an Emz gadget to push back assassins is crucial for survival.",
  "Hypercharges make your brawler glow purple and give them incredible stat boosts.",
  "Chuck placed his train posts to zoom straight to the enemy safe in Heist."
];

export const EN_PARAGRAPHS = [
  "By day, they are the world's most famous K-pop group, singing chart-topping hits and performing for massive crowds. But when the sun goes down, they trade their microphones for glowing swords. They are the secret demon hunters, protecting the city from shadowy monsters that lurk in the dark alleys. Their perfectly synchronized dance moves make them unstoppable in battle.",
  "Roblox is an endless universe where you can be anyone and play almost anything. One minute you might be escaping a spooky haunted house in a thrilling obby, and the next you could be running your own massive pizza restaurant. The best part is hanging out with friends, trading rare pets in Adopt Me, and customizing your avatar with awesome gear.",
  "The Brawl Stars match started and the countdown echoed across the canyon. The brawlers rushed toward the center of the map to grab the glowing purple gems before the enemy team could. With a flurry of rockets, cactus grenades, and powerful supers, the battle turned into absolute chaos. They only needed one more gem to start the final countdown and secure an epic victory!",
  "Imagine a Roblox game where your avatar joins a squad of K-pop demon hunters! You would have to complete rhythm mini-games to cast powerful magic spells and defeat monsters. Collecting enough points would unlock special glowing outfits and legendary pets to help you beat the ultimate shadow boss. It would definitely be the most popular experience on the entire platform!",
  "The arena was packed with thousands of screaming fans holding colorful lightsticks. Suddenly, the lights went out, but it wasn't a planned blackout. A giant rift opened in the sky above the stadium! Without missing a beat, the seven members drew their crystal weapons. They leaped into the air, transforming the concert into a massive, magical battlefield.",
  "Welcome to the most difficult obby in all of Roblox! You will have to jump across floating platforms, dodge spinning lasers, and carefully balance on thin tightropes. One wrong step means you fall all the way back to the beginning. Only the most skilled players with perfect timing and patience will ever reach the golden trophy at the top of the tower.",
  "Playing Brawl Ball is all about teamwork and passing the ball at the exact right moment. You can't just run straight at the enemy team, or they will blast you into pieces! You have to break the walls with supers, dodge incoming attacks, and sneak the ball into the net. Hearing the crowd roar when you score a trickshot is the best feeling in the world.",
  "Every member of the demon hunting idol group has a unique magical element. The main dancer controls lightning, moving so fast that he leaves a trail of sparks. The visual of the group uses ice shields to block enemy attacks, while the main rapper blasts shadow fiends with bursts of pure fire. When they combine their powers together, no monster stands a chance!",
  "Trading in Adopt Me can be super intense. You start with a common dog, and if you make smart trades, you might eventually work your way up to a legendary pet! It takes a lot of time to hatch eggs, age up your pets, and find players who want to make a fair deal. But the moment you finally get your dream pet, all that hard work is totally worth it.",
  "The Showdown map was getting smaller as the poisonous green gas closed in around the final three players. El Primo was hiding in the bushes with ten power cubes, waiting for someone to make a mistake. Suddenly, a wild Edgar leaped out of nowhere! A massive brawl broke out in the center of the map as the gas forced everyone into a final, chaotic showdown.",
  "What if there was a Roblox tycoon game where you managed an agency of demon hunting idols? You would have to build dance studios and vocal rooms to train their skills, while also building armories to upgrade their magical weapons. You could send them on missions to fight monsters in different dimensions, and use the loot to make your agency the biggest in the game!",
  "Heist mode requires a completely different strategy than gem grab. Your team has to decide whether to go all-in on attacking the enemy safe, or leave someone behind to defend your own. Brawlers who can deal massive damage over time, like Barley or Dynamike, are absolutely crucial. You have to break through the enemy defenses and melt their safe before they destroy yours!",
  "The secret to their power lies in the enchanted microphones they use. Each mic amplifies not only their voices but also their inner magical energy. When the main vocalist hits a glass-shattering high note, it sends out a sonic wave that disintegrates shadow monsters. They must always keep their voices protected, because singing is literally their ultimate weapon!",
  "In the game Arsenal, you have to master tons of different weapons to win. Every time you get an elimination, your weapon changes randomly. One second you might have a powerful sniper rifle, and the next you're stuck with a silly spellbook or a pizza box. The first person to get an elimination with the legendary golden knife wins the entire round!",
  "The mysterious Starr Park is a theme park full of strange secrets and powerful brawlers. Some say the brawlers are actually trapped inside the park, forced to battle in endless arenas. Every time you unlock a new brawler, you get a small piece of the puzzle. From the rollercoasters to the haunted houses, something is definitely not right at Starr Park.",
  "Hatching a cracked egg is always a gamble. Most of the time you just get a common cat or dog, which is still cute, but not super exciting. However, there is a tiny, tiny chance that a legendary pet might pop out! The moment the egg starts shaking and glows gold, everyone in the server gathers around to see what you got.",
  "A new rival idol group debuted recently, but there's a huge problem. They aren't demon hunters... they are actual demons in disguise! They use dark magic in their songs to hypnotize the fans. Now, our heroes have to challenge them to an ultimate dance battle. The winner gets to control the mystical energy of the entire city.",
  "Knockout is the most intense game mode by far. There are no respawns. If you get eliminated, you are out for the rest of the round! It creates a super tense atmosphere where every single shot matters. When it comes down to a 1 versus 3 situation, the pressure is massive, but pulling off an epic comeback feels absolutely incredible.",
  "Building a massive theme park in Theme Park Tycoon 2 takes weeks of dedication. You have to lay down all the paths, build terrifying rollercoasters from scratch, and make sure you have enough food stalls to keep your guests happy. Seeing hundreds of players visiting your park and riding your custom coasters is the best reward for all that hard work.",
  "The new season of Brawl Pass just dropped, and everyone is rushing to unlock the exclusive final tier skin. Completing daily and seasonal quests is the fastest way to earn tokens and progress through the pass. Some quests require you to win matches in specific modes, while others challenge you to deal a certain amount of damage with a specific brawler. The rewards, like pins, coins, and power points, are totally worth the grind.",
  "Mastering the art of dodging in Brawl Stars is what separates the average players from the pros. When you're facing a sharpshooter like Bea or Piper, you can't just walk in a straight line. You have to constantly zigzag, bait out their shots, and predict where they are going to aim. A perfectly timed juke can completely drain their ammo, leaving them completely defenseless and vulnerable to a counterattack.",
  "Every brawler in the game belongs to a specific class, like Assassin, Marksman, Artillery, or Tank. Understanding how these classes interact is the key to winning draft modes. You would never pick a close-range tank on a wide-open map, because enemy snipers would take you out before you could even get close! Building a balanced team composition is half the battle before the match even begins.",
  "Spike might look like a cute, smiling cactus, but his damage output is absolutely terrifying. His main attack explodes into sharp needles that spread out in all directions, making it incredibly hard to dodge. If you get caught directly in the center of his attack, it can instantly delete you. His super, a field of sticky spikes, slows down enemies and makes them easy targets for his team.",
  "In Gem Grab, the countdown timer is the most stressful part of the game. Once a team holds ten gems, a fifteen-second timer starts. If the team holding the gems manages to survive, they win. But if the gem carrier gets eliminated, all their gems spill onto the ground in a massive pile. One lucky super from an enemy brawler can instantly reverse the entire match at the very last second!",
  "Ash, the grumpy trash knight, gets stronger the angrier he becomes. As he takes damage or lands hits with his broom, his rage bar fills up. At maximum rage, his movement speed and attack damage are significantly boosted, turning him into an unstoppable cleaning machine. You have to be careful when fighting him, because attacking him only makes him madder and more dangerous!",
  "The legendary brawler Leon is a master of deception and stealth. His signature move allows him to create a clone of himself that runs forward, tricking enemies into attacking the wrong target. While the enemy team wastes their ammo on the fake Leon, the real one uses his smoke bomb super to turn invisible and sneak behind enemy lines, ready to unleash a barrage of spinning blades.",
  "Playing Duo Showdown requires constant communication and synergy with your teammate. Unlike solo mode, you can respawn as long as your partner stays alive for fifteen seconds. This leads to intense moments where one player is desperately hiding in the bushes, trying to survive against multiple teams just long enough for their teammate to respawn and turn the fight around.",
  "Colette's mechanics are completely unique because her attacks deal damage based on the enemy's current health. If she hits a massive tank like Frank, she deals an unbelievable amount of damage in a single shot. However, finishing off enemies with low health can be tricky since her damage scales down. You have to master her combo, which involves hitting two basic attacks and finishing with her charging super.",
  "The environmental hazards on some maps can be just as dangerous as the enemy players. From jump pads that launch you across the arena to teleporters that instantly transport you behind enemy lines, you have to use the map to your advantage. There are even minecarts that roll through the center of certain Gem Grab maps, dealing heavy damage and blocking shots for whoever gets in the way.",
  "Max is a hyperactive superhero who is obsessed with speed and energy drinks. She has four ammo slots instead of the usual three, allowing her to fire a rapid barrage of electrical blasts. Her super creates an aura that massively boosts the movement speed of herself and her nearby teammates. When she activates it, her entire team can rush the objective or escape from a bad situation in the blink of an eye.",
  "Gadgets add an extra layer of strategy to every match. Each brawler has two unique gadgets to choose from before the game starts, but they can only be used three times per match. A perfectly timed gadget, like Crow's slowing toxin or Shelly's dash, can completely change the outcome of a duel. Knowing when to save your gadgets and when to use them is a crucial skill for climbing the ranks.",
  "Squeak is an adorable alien made entirely out of dog drool, created by Colonel Ruffs. His explosive blobs stick to walls, the floor, and even enemy brawlers! After a short delay, they detonate with a satisfying pop, dealing massive area damage. His attacks are perfect for controlling tight choke points and forcing the enemy team to spread out and retreat.",
  "Star Powers unlock a brawler's true potential once they reach power level nine. These passive abilities fundamentally change how a brawler is played. For example, Bo's circling eagle lets him see twice as far into bushes, completely shutting down sneaky assassins. Choosing the right Star Power for the right map is a decision that can make or break a competitive match.",
  "In Brawl Ball, defending your goal against a coordinated push can feel overwhelming. If the enemy team breaks down your walls and walks the ball right up to your net, you have to act fast. Brawlers with knockback abilities, like Gale with his freezing snowstorm super or Gene with his gadget, are incredibly valuable because they can push the ball carrier away and save the game.",
  "Mega Pig is a massive club event where players team up to earn incredible rewards. You have to play special matches with crazy modifiers, like infinite ammo, super speedy brawlers, or maps filled with toxic bushes. Winning these matches contributes to smashing the giant pig. At the end of the event, the pig breaks open, showering the entire club with Starr Drops, coins, and bling!",
  "Janet is a stunt pilot who literally takes to the skies during battle. Her super allows her to activate her jetpack and fly over walls, water, and enemy attacks, making her completely invincible while in the air. She drops rockets on the enemies below as she flies by, making her one of the most annoying brawlers to deal with when you are trying to hold a position.",
  "The map maker feature lets players unleash their creativity and design their own crazy arenas. Some maps are intricately balanced for competitive play, while others are absolute chaos, filled with dozens of jump pads and teleporters. Every day, the community votes on the best player-made map, and the winner gets featured in the main game for everyone to play and enjoy.",
  "Playing as a thrower, like Dynamike or Grom, requires you to constantly use walls for protection. Since their attacks can go over obstacles, they thrive in maps with lots of cover. However, they are incredibly vulnerable at close range. If an assassin like Edgar jumps over the wall and gets right next to a thrower, it's usually game over in a matter of seconds.",
  "The chaotic nature of 5v5 game modes completely flips traditional strategies upside down. With ten players spamming attacks, supers, and gadgets all at once, the screen becomes a blinding explosion of colors and sound effects. You have to keep track of multiple objectives simultaneously, making sure your team doesn't get overwhelmed by a massive, five-person push on one side of the map.",
  "Tower Defense Simulator is a game where strategy and placement mean everything. You start with basic scouts and snipers to fend off the early waves of zombies. As you earn cash, you can place incredibly powerful units like minigunners, commanders, and accelerators. Surviving the final wave against the massive boss requires perfect coordination with your team and upgrading your towers to maximum level.",
  "Welcome to Bloxburg is the ultimate life simulation game on Roblox. Unlike most games, you actually have to work a job to earn money, whether it's delivering pizzas on a moped or cutting hair at the salon. With your hard-earned cash, you can enter build mode and design your dream house from scratch, picking out every single piece of furniture, wallpaper, and lighting fixture.",
  "In Murder Mystery 2, every round starts with intense paranoia. The innocent players have to run and hide, collecting coins while trying to figure out who is secretly the murderer. The sheriff is the only player with a gun, and their job is to shoot the killer before it's too late. But if the sheriff shoots an innocent person by mistake, they are eliminated instantly!",
  "Adopt Me isn't just about pets; it's an entire virtual economy. The value of pets fluctuates constantly based on demand and rarity. A pet from an old, limited-time egg might suddenly become extremely valuable, leading to massive trading wars in the town square. Players spend hours negotiating, hoping to secure a win in a trade and move one step closer to their dream inventory.",
  "Developing your own game in Roblox Studio is surprisingly easy to learn but incredibly difficult to master. You can use basic blocks and cylinders to build the map, and write scripts in Lua to make the game actually work. Millions of players have turned their wild imaginations into fully playable games, creating everything from massive roleplaying cities to intense first-person shooters.",
  "Arsenal is famous for its fast-paced, chaotic gameplay and hilarious voice announcers. You don't get to choose your loadout; instead, your weapon changes automatically every time you score a kill. You have to adapt instantly, swapping from a rapid-fire assault rifle to a slow-reloading musket, or even a magical spellbook. The matches are short, intense, and constantly keep you on your toes.",
  "Scuba diving in games like SharkBite is a terrifying experience. One player is chosen to be a massive, hungry great white shark, while everyone else spawns on boats armed with weapons. The survivors have to drive around the ocean and shoot the shark before it completely destroys their boat. Once your boat sinks, you are left swimming for your life in the open water!",
  "The Hunt was a massive, platform-wide event where players had to travel across dozens of different Roblox games to collect hidden badges. From completing a special obby in a tycoon game to solving a puzzle in a horror game, the challenges were incredibly diverse. Earning enough badges unlocked exclusive, limited-time avatar accessories that proved you were a dedicated badge hunter.",
  "Piggy took the survival horror genre by storm with its deep lore and puzzle-solving mechanics. You are trapped in a creepy map and have to find colored keys, wrenches, and gears to unlock doors and escape. All the while, a terrifying, bat-wielding creature is slowly chasing you. Learning the layout of the map and outsmarting the monster is the only way to survive.",
  "Earning the Halo in Royale High is the ultimate symbol of luck and status. To get one, you have to visit the fountain of dreams, read a short story, and choose the correct answer. Even if you pick the right option, the chance of actually winning a glowing halo is incredibly low. Because they are so rare, players will trade massive amounts of diamonds and rare sets just to get one.",
  "In Natural Disaster Survival, a peaceful map can turn into an absolute nightmare in seconds. A siren blares, warning the server that a disaster is approaching. Suddenly, a massive tornado might tear through the buildings, or a volcano might erupt, raining fiery boulders from the sky. You have to constantly adapt, finding sturdy shelter or running to high ground to avoid being wiped out.",
  "Lumber Tycoon 2 is a classic game about chopping down trees and building a massive base. It sounds simple, but you have to buy increasingly powerful axes to chop down rare, glowing wood located in dangerous areas like the top of a volcano. You have to physically load the logs into your truck, drive them to the sawmill, and process them into planks to build your dream factory.",
  "Doors is one of the highest-quality horror games on the entire platform. You are trapped in a haunted hotel and must walk through one hundred numbered doors to escape. Every room is randomly generated, and terrifying entities lurk in the dark. If the lights start flickering, you have to immediately hide in a closet or under a bed before the monster called Rush zooms through the hallway.",
  "The customization options for your Roblox avatar are practically endless. By mixing and matching different layered clothing items, 3D accessories, and animated faces, you can create a look that is completely unique. Some players prefer the classic, blocky look, while others spend thousands of Robux to look like a realistic superhero or a massive, glowing anime character.",
  "Speed Run 4 is a fast-paced platformer where you run through thirty different brightly colored levels as fast as possible. Your character moves at breakneck speeds, and you have to time your jumps perfectly over massive gaps and obstacles. The bouncy techno music keeps your adrenaline pumping as you try to beat your personal best time and unlock new dimensions to run through.",
  "Bee Swarm Simulator is a surprisingly deep game about collecting pollen and managing a massive hive of bees. Different bees have different stats and abilities, and you have to feed them special treats to level them up and mutate them. As you unlock new areas of the map, you can fight massive bosses like the King Beetle and the Tunnel Bear to earn rare loot and royal jellies.",
  "Driving in Vehicle Simulator is all about showing off your expensive rides and racing your friends. The map is a massive city with winding highways, stunt ramps, and drag racing strips. You can customize your cars with different paint jobs, spoilers, and engine upgrades. Earning enough money to buy the ultimate hypercar takes hours of grinding and winning high-stakes races.",
  "Playing Hide and Seek Extreme is hilarious because the maps are absolutely massive. You play as a tiny character hiding in a giant bedroom, kitchen, or workshop. The seeker is frozen for one minute while everyone scrambles to find the perfect hiding spot, like inside a cereal box or behind a giant book. The tension of watching the seeker walk right past your hiding spot is incredible.",
  "FNF or Friday Night Funkin' style rhythm games are extremely popular in Roblox. You face off against an opponent in a rap battle, hitting the four directional arrows exactly on the beat. The songs get progressively faster and more complicated, requiring lightning-fast reflexes and perfect finger coordination. A single missed note can ruin your combo and cause you to lose the battle.",
  "Slap Battles is a chaotic arena game where the only objective is to slap other players off the edge of the map. Every time you successfully slap someone, you earn slaps which act as currency to unlock hilarious new gloves. Some gloves give you a massive speed boost, while others let you summon a bus to run over your enemies or trap them in a giant block of ice.",
  "The group's vocal practice room was lined with soundproof foam, but it wasn't just to keep the music from bothering the neighbors. The walls were actually enchanted to contain the explosive magical energy of their voices. When the main vocalist practiced his highest notes, the resulting sonic boom was strong enough to shatter ordinary glass and obliterate any low-level shadow fiends nearby.",
  "Their fandom, known as 'Luminaries,' had absolutely no idea that their favorite idols were secretly fighting the forces of darkness. To the fans, the glowing lightsticks were just a fun way to support the group at concerts. In reality, the lightsticks were acting as magical conduits, harvesting the positive energy of the crowd and channeling it directly into the idols' weapons during a battle.",
  "The choreographer for the group was a legendary martial arts master who disguised ancient combat forms as trendy dance routines. Every slide, spin, and hand gesture had a dual purpose. When the idols performed their hit song on a music show, they were actually practicing the exact sequence of movements needed to cast a massive, stage-clearing spell of pure radiant light.",
  "The youngest member of the group, known as the maknae, possessed a rare ability to see through demonic illusions. While the rest of the group was easily fooled by a monster disguising itself as a staff member, the maknae could see its true, shadowy form. He used his enchanted microphone cord like a glowing lasso, tying up the demon before it could sabotage their live broadcast.",
  "Music video shoots were incredibly dangerous, not because of the stunts, but because the bright lights and loud music naturally attracted creatures from the shadow realm. During the filming of their latest single, an army of gargoyles attacked the set. The director thought it was a surprise special effect and kept the cameras rolling, capturing an epic, real-life magical battle on film.",
  "The group's fashion stylist was an expert in magical tailoring. Every sequin on their stage outfits was actually a tiny, protective rune. The heavy leather jackets and silver chains weren't just for looking cool; they were enchanted armor designed to deflect dark magic. Even their combat boots were charmed, allowing them to leap thirty feet into the air and land without making a single sound.",
  "A rival idol group debuted a few months ago, and they were gaining popularity at an alarming rate. However, our heroes soon discovered a terrifying secret: the rival group was entirely composed of high-ranking vampires! They were using their catchy songs to hypnotize the public. A secret, underground dance battle was the only way to break the spell and banish them back to the shadows.",
  "The group's leader carried a custom-made electric guitar that doubled as a massive broadsword. When he strummed a power chord, the guitar released a wave of lightning that could stun a dozen monsters at once. During a particularly intense fight on the rooftop of their agency building, he used a massive guitar solo to summon a thunderstorm and wash away the shadow army.",
  "Award show season was always the most stressful time of the year. Not only did they have to prepare special performances and worry about winning trophies, but the massive gathering of positive energy at the arena always attracted a demon lord. They often had to sneak out during the commercial breaks, fight a massive boss monster in the parking lot, and rush back in time to accept their award.",
  "The visual of the group, known for his perfect looks and charming smile, wielded the element of ice. He could freeze a demon solid with just a glance and a flick of his wrist. During a summer fan meeting, a fiery hellhound tried to attack the crowd. He gracefully stepped forward, smiled at the fans, and secretly stomped his foot, freezing the beast into a beautiful ice sculpture.",
  "The agency's CEO was a mysterious figure who rarely left his office on the top floor. Rumor had it that he was a centuries-old sorcerer who founded the entertainment company specifically to fund his war against the shadow realm. He provided the idols with endless resources, magical training, and the best songwriters in the industry, ensuring they stayed at the top of the charts.",
  "The rap line of the group specialized in offensive magic. Their fast-paced, aggressive verses acted as rapid-fire incantations. When the two main rappers performed a duet, they could summon a storm of explosive fireballs that danced to the beat of the music. They often competed with each other to see who could banish the most monsters during a single three-minute song.",
  "A massive dark portal opened in the middle of their sold-out stadium concert, right as the beat dropped. The idols didn't panic. They smoothly transitioned into a new formation, drawing their crystal weapons in perfect sync with the music. The crowd thought it was a surprise theatrical performance, cheering wildly as the group fought back a horde of flying shadow gargoyles on stage.",
  "Healing magic was incredibly rare, but the group's lead vocalist had the gift. If a member was injured during a fight, he could sing a soft, acoustic melody that would instantly mend their wounds and restore their stamina. His voice was so pure that just listening to his solo tracks could cure minor illnesses and drive away bad nightmares for the fans who streamed his music.",
  "The dance break of their title track was legendary. It involved a complex sequence of acrobatic flips and synchronized kicks. What the fans didn't know was that this specific dance break was a powerful sealing ritual. Every time they performed it on live television, the magical energy broadcasted across the nation, reinforcing the magical barriers that protected the entire city from demons.",
  "The idol's dorm was heavily protected by dozens of magical wards and security spells. To any normal person, it looked like a luxurious penthouse apartment. But to a creature of the dark, it was an impenetrable fortress of pure light. The refrigerator was stocked with magical potions disguised as energy drinks, and the closet was an armory full of enchanted weapons and stylish outfits.",
  "During a worldwide live stream, the power suddenly went out in the studio, plunging the room into total darkness. The fans in the chat panicked, but the idols simply activated the glowing crystals embedded in their rings. The stream continued with an eerie, magical lighting effect as the group casually fought off a squad of shadow assassins, pretending it was an interactive horror game.",
  "The main dancer's enchanted sneakers allowed him to run on walls and ceilings without falling. This came in incredibly handy when fighting giant spider-demons that liked to hide in the rafters of concert halls. He would sprint up the walls, launch himself into the air, and strike down the monsters with a barrage of glowing, magical kicks, all while maintaining a perfect smile.",
  "An ancient prophecy stated that seven warriors of light would banish the shadow king using the power of harmony. The idols initially thought it was just a cool concept for their next album, until the shadow king actually showed up at their record label headquarters. They had to quickly learn the ancient harmonic chord and blast it through the building's massive speaker system to save the day.",
  "Maintaining their secret identities was harder than fighting the monsters. They constantly had to make up excuses for their injuries, blaming epic sword-fight cuts on 'clumsy dance practice accidents.' The paparazzi were always trying to get a scoop, but whenever a photographer managed to snap a picture of a monster, the magical aura of the idols caused the camera film to completely blur."
];

export const KOR_SENTENCES = [
  "케이팝 아이돌은 그림자 악마들과 싸우면서 춤을 추었습니다.",
  "그 멋진 한정판 액세서리를 사려면 로벅스가 더 필요해요.",
  "콜트는 브롤스타즈에서 벽을 부수기 위해 특수 공격을 사용했습니다.",
  "그녀는 고음을 내어 괴물을 영원히 쫓아냈습니다.",
  "저는 입양하세요에서 서리 드래곤을 메가 네온 유니콘과 교환했습니다.",
  "스파이크는 수풀 속으로 선인장 수류탄을 던졌습니다.",
  "악마 사냥꾼들은 무대 위에서 마법의 빛으로 빛났습니다.",
  "로블록스에서 거대한 오비를 만드는 데는 많은 테스트가 필요합니다.",
  "쉘리는 적 팀을 기습하기 위해 키 큰 풀밭에 숨었습니다.",
  "그들의 새 뮤직비디오는 사실 뱀파이어와의 비밀 전투였습니다.",
  "새로운 한정판 아이템으로 제 아바타가 정말 멋져 보여요!",
  "엘 프리모는 열 개의 보라색 보석을 가지고 공중으로 높이 점프했습니다.",
  "리드 싱어는 완벽한 고음을 내면서 불덩어리를 피했습니다.",
  "제 네온 플라이 라이드 섀도우 드래곤은 서버에서 가장 희귀한 펫이에요!",
  "불은 수풀을 뚫고 돌진하여 적 팀을 기습했습니다.",
  "분홍빛 번쩍임과 함께 괴물들은 마법의 거품에 갇혔습니다.",
  "이 불가능한 타워 오브 헬 레벨을 깨는 것을 도와줄 수 있나요?",
  "크로우는 보석 운반자가 도망치는 것을 막기 위해 독단검을 던졌습니다.",
  "댄스 브레이크 동안 그들의 응원봉이 빛나는 무기로 변했습니다.",
  "우리는 블록스버그에서 꿈의 집을 짓는 데 몇 시간을 보냈습니다.",
  "파이퍼는 맵 반대편에서 저격하여 마지막 순간에 위기를 구했습니다.",
  "궁극의 그림자 야수가 무대에 나타나자 음악이 희미해졌습니다.",
  "전설적인 스타 드롭을 얻어서 멋진 새 스킨을 받았어요!",
  "오비에서 붉은 용암 블록을 밟지 않도록 조심하세요.",
  "아이돌이 유령 군대를 베어 넘기자 관중들은 환호했습니다.",
  "머더 미스터리에서 숨바꼭질을 하는 것은 항상 너무 긴장돼요!",
  "레온은 연막탄 투명화를 사용하여 적 팀을 몰래 지나갔습니다.",
  "어둠의 포털을 완전히 파괴한 불꽃놀이와 함께 콘서트가 끝났습니다.",
  "방금 신화 알을 부화시켜서 정말 놀라운 것을 얻었어요!",
  "다이너마이크는 금고 바로 위에 거대한 폭발 통을 던졌습니다.",
  "피기가 우리를 잡기 전에 모든 문을 열어야 해요.",
  "베이스 드롭이 하급 악마들을 모두 소탕하는 충격파를 보냈습니다.",
  "모티스는 마지막 파워 큐브를 잡기 위해 삽을 들고 앞으로 돌진했습니다.",
  "역대 가장 큰 사탕 공장을 짓는 제 타이쿤에 오신 것을 환영합니다!",
  "래퍼의 벌스는 너무 빨라서 얼음 악마의 갑옷을 산산조각 냈습니다.",
  "그들은 순간이동 마법을 노래의 비트에 맞춰 동기화했습니다.",
  "팬들의 환호가 그룹의 궁극의 응원봉 공격을 충전했습니다.",
  "그녀는 순수한 음파로 만든 방패를 사용하여 그림자 화살을 튕겨냈습니다.",
  "백업 댄서들은 사실 변장한 엘리트 몬스터 헌터들이었습니다.",
  "거대한 유령이 팬 미팅을 망치려 했지만 아이돌들이 처리했습니다.",
  "그들의 컴백 무대에는 뱀파이어 군주와의 실제 마법 결투가 포함되었습니다.",
  "그는 마이크 스탠드를 지팡이처럼 돌려 고블린들을 쓸어버렸습니다.",
  "빛나는 무대 의상은 특별한 대마법 실로 짜여졌습니다.",
  "그들이 화음을 맞출 때 보호 장벽이 경기장 전체를 둘러쌉니다.",
  "앨범의 비밀 트랙은 사실 포털을 봉인하는 주문이었습니다.",
  "브룩헤이븐에서 엄청 빨리 달릴 수 있게 해주는 게임패스를 드디어 샀어요.",
  "플리 더 퍼실리티에서 야수가 우리를 잡기 전에 컴퓨터를 해킹하고 탈출해야 했습니다.",
  "제 꿈은 할로윈 이벤트 기간 동안 머리 없는 기사 머리를 얻는 것입니다.",
  "펫 시뮬레이터 99의 거래 광장은 항상 플레이어들로 붐빕니다.",
  "자연재해 생존 게임에서 쓰나미 라운드를 무사히 살아남았습니다.",
  "닌자 레전드에서 스탯을 쌓으려면 최대한 빨리 클릭해야 합니다.",
  "새로운 배드워즈 업데이트가 아이템 상점에 엄청나게 강력한 검을 추가했습니다.",
  "우리가 은행을 털 수 있게 제일브레이크에서 차량을 소환해 줄 수 있나요?",
  "플리즈 도네이트에서 스탠드를 꾸미고 수백 로벅스를 벌었습니다.",
  "슬렌더맨을 보지 마세요. 안 그러면 화면이 완전히 지지직거릴 거예요!",
  "블록스버그에 비밀 지하 벙커를 짓는 데 엄청난 돈이 들었습니다.",
  "보는 보석 광산을 보호하기 위해 폭발 지뢰를 완벽하게 설치했습니다.",
  "서지는 자신을 최대 레벨로 업그레이드하고 모든 공격을 피하기 시작했습니다.",
  "틱의 머리가 분리되어 적 브롤러를 독가스 속까지 쫓아갔습니다.",
  "앰버는 불길을 뿜어내어 맵 중앙 전체에 불을 붙였습니다.",
  "교활한 코델리우스가 당신을 그림자 세계로 끌어들이는 것을 조심해야 해요!",
  "진은 마법의 손 특수 공격을 사용하여 적 보석 운반자를 벽 너머로 끌어당겼습니다.",
  "버즈는 어뢰 부표를 사용하여 벽을 붙잡고 위험에서 벗어났습니다.",
  "완벽한 타이밍의 타라 블랙홀로 팀을 전멸시키는 것은 정말 짜릿합니다.",
  "페니는 아무도 쉽게 파괴할 수 없는 벽 뒤에 박격포를 배치했습니다.",
  "암살자들을 밀어내기 위해 엠즈 가젯을 사용하는 것은 생존에 필수적입니다.",
  "하이퍼차지는 브롤러를 보라색으로 빛나게 하고 놀라운 스탯 증가를 제공합니다.",
  "척은 하이스트에서 적 금고로 바로 돌진하기 위해 기차 기둥을 설치했습니다."
];

export const KOR_PARAGRAPHS = [
  "낮에는 전 세계적으로 가장 유명한 케이팝 그룹으로서 차트를 휩쓰는 히트곡을 부르고 수많은 관중 앞에서 공연을 펼칩니다. 하지만 해가 지면 마이크를 빛나는 검으로 바꿉니다. 그들은 어두운 골목에 숨어 있는 그림자 괴물들로부터 도시를 보호하는 비밀 악마 사냥꾼들입니다. 그들의 완벽하게 훈련된 댄스 동작은 전투에서 그들을 무적 상태로 만듭니다.",
  "로블록스는 여러분이 누구든 될 수 있고 거의 모든 것을 플레이할 수 있는 끝없는 우주입니다. 어느 순간에는 스릴 넘치는 오비에서 오싹한 유령의 집을 탈출하다가도, 다음 순간에는 자신만의 거대한 피자 가게를 운영하고 있을 수도 있습니다. 가장 좋은 점은 친구들과 어울리고, 입양하세요에서 희귀한 펫을 교환하고, 멋진 장비로 아바타를 꾸미는 것입니다.",
  "브롤스타즈 매치가 시작되었고 협곡 전체에 카운트다운이 울려 퍼졌습니다. 브롤러들은 적 팀보다 먼저 빛나는 보라색 보석을 차지하기 위해 맵의 중앙으로 돌진했습니다. 로켓, 선인장 수류탄, 그리고 강력한 특수 공격이 난무하며 전투는 완전한 혼란으로 변했습니다. 마지막 카운트다운을 시작하고 엄청난 승리를 거두려면 보석이 딱 하나 더 필요했습니다!",
  "아바타가 케이팝 악마 사냥꾼 팀에 합류하는 로블록스 게임을 상상해 보세요! 리듬 미니 게임을 완료하여 강력한 마법 주문을 시전하고 괴물을 물리쳐야 할 것입니다. 포인트를 충분히 모으면 특별한 빛나는 의상과 전설적인 펫이 잠금 해제되어 궁극의 그림자 보스를 물리치는 데 도움이 됩니다. 이 게임은 단연 전체 플랫폼에서 가장 인기 있는 경험이 될 것입니다!",
  "경기장은 다채로운 응원봉을 들고 환호하는 수천 명의 팬들로 가득 찼습니다. 갑자기 불이 꺼졌지만 그것은 계획된 정전이 아니었습니다. 경기장 위 하늘에 거대한 균열이 열린 것입니다! 한 치의 흐트러짐도 없이 일곱 명의 멤버들은 크리스탈 무기를 뽑아 들었습니다. 그들은 공중으로 도약하며 콘서트를 거대한 마법의 전장으로 바꾸어 놓았습니다.",
  "로블록스 전체에서 가장 어려운 오비에 오신 것을 환영합니다! 공중에 떠 있는 플랫폼을 뛰어넘고, 빙빙 도는 레이저를 피하고, 얇은 외줄 위에서 조심스럽게 균형을 잡아야 합니다. 발을 한 번만 잘못 디디면 맨 처음으로 다시 떨어지게 됩니다. 완벽한 타이밍과 인내심을 가진 가장 능숙한 플레이어만이 탑 꼭대기에 있는 황금 트로피에 도달할 수 있습니다.",
  "브롤볼을 플레이하는 것은 팀워크와 정확한 순간에 공을 패스하는 것이 전부입니다. 적 팀을 향해 일직선으로 달려가기만 해서는 안 됩니다. 그렇지 않으면 조각나버릴 것입니다! 특수 공격으로 벽을 부수고, 날아오는 공격을 피하고, 네트 안으로 공을 몰래 넣어야 합니다. 트릭샷을 성공시켰을 때 군중이 환호하는 소리를 듣는 것은 세상에서 가장 기분 좋은 일입니다.",
  "악마 사냥꾼 아이돌 그룹의 각 멤버는 고유한 마법 원소를 가지고 있습니다. 메인 댄서는 번개를 다루며 너무 빨리 움직여서 불꽃을 남깁니다. 그룹의 비주얼 담당은 얼음 방패를 사용하여 적의 공격을 막고, 메인 래퍼는 순수한 불꽃을 폭발시켜 그림자 마귀들을 날려버립니다. 그들이 힘을 합치면 어떤 괴물도 상대가 되지 않습니다!",
  "입양하세요에서 거래를 하는 것은 엄청난 긴장감을 유발할 수 있습니다. 흔한 강아지로 시작하지만 똑똑하게 거래를 하다 보면 전설 펫까지 올라갈 수도 있습니다! 알을 부화시키고, 펫을 성장시키고, 공정한 거래를 원하는 플레이어를 찾는 데는 많은 시간이 걸립니다. 하지만 마침내 꿈에 그리던 펫을 얻는 순간 그 모든 노력은 완벽하게 보상받습니다.",
  "최후의 3명의 플레이어를 향해 유독한 녹색 가스가 좁혀지면서 쇼다운 맵이 점점 작아지고 있었습니다. 엘 프리모는 10개의 파워 큐브를 들고 누군가 실수하기를 기다리며 수풀 속에 숨어 있었습니다. 갑자기 야생의 에드거가 어디선가 튀어나왔습니다! 가스가 모두를 마지막 혼돈의 대결로 몰아넣으면서 맵 중앙에서 거대한 난투가 벌어졌습니다.",
  "악마를 사냥하는 아이돌 기획사를 운영하는 로블록스 타이쿤 게임이 있다면 어떨까요? 그들의 기술을 훈련시키기 위해 댄스 연습실과 보컬 룸을 짓고, 마법 무기를 업그레이드하기 위해 무기고도 건설해야 할 것입니다. 여러 차원에서 괴물과 싸우도록 그들을 임무에 보내고, 얻은 전리품을 사용하여 게임에서 가장 큰 기획사로 만들 수 있습니다!",
  "하이스트 모드는 젬 그랩과는 완전히 다른 전략이 필요합니다. 적의 금고를 공격하는 데 올인할지, 아니면 누군가를 남겨서 우리 금고를 방어할지 결정해야 합니다. 발리나 다이너마이크처럼 지속적으로 엄청난 피해를 줄 수 있는 브롤러는 절대적으로 중요합니다. 적의 금고가 우리 금고를 파괴하기 전에 먼저 방어선을 뚫고 적의 금고를 녹여버려야 합니다!",
  "그들의 힘의 비밀은 그들이 사용하는 마법의 마이크에 있습니다. 각각의 마이크는 그들의 목소리뿐만 아니라 내면의 마법 에너지를 증폭시킵니다. 메인 보컬이 유리를 깨뜨릴 듯한 고음을 낼 때, 그것은 그림자 괴물들을 분해하는 음파를 내보냅니다. 노래를 부르는 것이 그들의 궁극적인 무기이기 때문에 그들은 항상 목소리를 보호해야 합니다!",
  "아스널 게임에서 이기려면 수많은 다양한 무기를 마스터해야 합니다. 상대를 처치할 때마다 무기가 무작위로 바뀝니다. 어느 순간 강력한 저격소총을 들고 있다가 다음 순간에는 우스꽝스러운 마법책이나 피자 상자를 들고 있을 수도 있습니다. 전설적인 황금 칼로 첫 킬을 따내는 사람이 그 라운드 전체에서 우승하게 됩니다!",
  "신비로운 스타 파크는 기이한 비밀과 강력한 브롤러들로 가득 찬 테마파크입니다. 어떤 이들은 브롤러들이 실제로 끝없는 경기장에서 싸우도록 강요받으며 공원 안에 갇혀 있다고 말합니다. 새로운 브롤러를 잠금 해제할 때마다 퍼즐의 작은 조각을 얻게 됩니다. 롤러코스터부터 유령의 집까지, 스타 파크에는 분명히 무언가 잘못된 것이 있습니다.",
  "금이 간 알을 부화시키는 것은 항상 도박입니다. 대부분의 경우 여전히 귀엽지만 엄청 흥미롭지는 않은 흔한 고양이나 개가 나옵니다. 하지만 전설 펫이 튀어나올 아주 희박한 확률이 있습니다! 알이 흔들리기 시작하고 황금빛으로 빛나는 순간, 서버의 모든 사람이 당신이 무엇을 얻었는지 보기 위해 주위로 모여듭니다.",
  "최근 새로운 라이벌 아이돌 그룹이 데뷔했지만 큰 문제가 있습니다. 그들은 악마 사냥꾼이 아니라... 변장한 진짜 악마입니다! 그들은 팬들에게 최면을 걸기 위해 노래에 흑마법을 사용합니다. 이제 우리의 영웅들은 궁극의 댄스 배틀로 그들에게 도전해야 합니다. 승자는 도시 전체의 신비로운 에너지를 지배하게 될 것입니다.",
  "녹아웃은 단연코 가장 긴장감 넘치는 게임 모드입니다. 부활은 없습니다. 만약 탈락하면 그 라운드 내내 제외됩니다! 이것은 모든 공격 하나하나가 중요한 엄청나게 팽팽한 분위기를 조성합니다. 1대 3 상황이 되면 압박감은 엄청나지만, 멋진 역전승을 해냈을 때는 절대적으로 짜릿한 기분이 듭니다.",
  "테마파크 타이쿤 2에서 거대한 테마파크를 짓는 데는 몇 주간의 헌신이 필요합니다. 모든 길을 깔고, 무시무시한 롤러코스터를 처음부터 만들고, 손님들을 기쁘게 할 충분한 음식 가판대가 있는지 확인해야 합니다. 수백 명의 플레이어가 당신의 공원을 방문하고 맞춤 제작한 롤러코스터를 타는 것을 보는 것은 그 모든 노력에 대한 최고의 보상입니다.",
  "브롤 패스의 새로운 시즌이 막 시작되었고, 모두가 독점적인 최종 티어 스킨을 잠금 해제하기 위해 서두르고 있습니다. 일일 퀘스트와 시즌 퀘스트를 완료하는 것이 토큰을 얻고 패스를 진행하는 가장 빠른 방법입니다. 핀, 코인, 파워 포인트와 같은 보상들은 열심히 노력할 가치가 충분합니다.",
  "브롤스타즈에서 피하기 기술을 마스터하는 것이 평범한 플레이어와 프로를 구분하는 기준입니다. 비나 파이퍼 같은 명사수를 상대할 때는 그냥 일직선으로 걸어가면 안 됩니다. 끊임없이 지그재그로 움직이며 적의 공격을 유도하고 조준할 곳을 예측해야 합니다. 완벽한 타이밍의 회피는 적의 탄약을 완전히 고갈시켜 방어할 수 없게 만들고 반격에 취약하게 만듭니다.",
  "게임의 모든 브롤러는 암살자, 명사수, 포병, 또는 탱커와 같은 특정 클래스에 속합니다. 이러한 클래스가 어떻게 상호 작용하는지 이해하는 것이 드래프트 모드에서 승리하는 열쇠입니다. 적의 저격수가 다가가기도 전에 당신을 쓰러뜨릴 것이기 때문에 탁 트인 맵에서는 절대 근거리 탱커를 고르지 않을 것입니다! 균형 잡힌 팀 구성을 만드는 것은 매치가 시작되기도 전 승리의 절반입니다.",
  "스파이크는 귀엽고 웃는 선인장처럼 보일지 모르지만 그의 공격력은 절대적으로 무섭습니다. 그의 기본 공격은 사방으로 퍼지는 날카로운 바늘로 폭발하여 피하기가 엄청나게 어렵습니다. 그의 공격의 정중앙에 잡히면 즉시 삭제될 수 있습니다. 그의 특수 공격인 끈적이는 가시 밭은 적을 늦추고 그의 팀이 쉽게 공격할 수 있는 목표물로 만듭니다.",
  "젬 그랩에서 카운트다운 타이머는 게임에서 가장 긴장되는 부분입니다. 한 팀이 보석 열 개를 보유하게 되면 15초의 타이머가 시작됩니다. 보석을 든 팀이 살아남는다면 승리합니다. 하지만 보석 운반자가 쓰러지면 그들의 모든 보석이 거대한 더미가 되어 바닥에 쏟아집니다. 적 브롤러의 운 좋은 특수 공격 하나가 마지막 순간에 매치 전체를 단숨에 역전시킬 수 있습니다!",
  "심술궂은 쓰레기 기사 애쉬는 분노할수록 더 강해집니다. 피해를 입거나 빗자루로 상대를 때리면 분노 게이지가 채워집니다. 분노가 최대치일 때 그의 이동 속도와 공격력이 크게 증가하여 멈출 수 없는 청소 기계로 변신합니다. 그를 공격하면 그를 더 화나고 위험하게 만들기 때문에 그와 싸울 때는 조심해야 합니다!",
  "전설 브롤러 레온은 속임수와 은신술의 대가입니다. 그의 상징적인 기술은 자신의 복제본을 만들어 앞으로 달려가게 하여 적들이 잘못된 대상을 공격하도록 속이는 것입니다. 적 팀이 가짜 레온에게 탄약을 낭비하는 동안 진짜 레온은 연막탄 특수 공격을 사용하여 투명해진 채 적진 뒤로 몰래 숨어들어 회전하는 표창을 퍼부을 준비를 합니다.",
  "듀오 쇼다운을 플레이하려면 팀원과의 지속적인 소통과 시너지 효과가 필요합니다. 솔로 모드와 달리 파트너가 15초 동안 살아있기만 하면 다시 부활할 수 있습니다. 한 플레이어가 여러 팀을 상대로 수풀 속에 필사적으로 숨어 팀원이 다시 부활하여 싸움을 역전시킬 수 있을 때까지 살아남으려는 긴장감 넘치는 순간들이 이어집니다.",
  "콜레트의 메커니즘은 적의 현재 체력에 비례해 피해를 주기 때문에 완전히 독특합니다. 만약 프랭크와 같이 거대한 탱커를 맞히면 한 번의 공격으로 믿을 수 없을 만큼 엄청난 피해를 줍니다. 특수 공격 돌진으로 마무리하는 그녀의 콤보를 마스터해야 합니다.",
  "일부 맵의 환경적 위험 요소는 적 플레이어만큼이나 위험할 수 있습니다. 맵을 가로질러 날려 보내는 점프 패드부터 적진 뒤로 즉시 이동시켜 주는 텔레포터까지, 맵을 유리하게 활용해야 합니다. 특정 젬 그랩 맵의 중앙을 구르며 엄청난 피해를 주고 길을 가로막는 사람의 공격을 차단하는 광산 수레도 있습니다.",
  "맥스는 속도와 에너지 음료에 푹 빠진 과잉 행동을 하는 슈퍼 히어로입니다. 그녀는 일반적인 세 개가 아닌 네 개의 탄약 슬롯을 가지고 있어 전기 블래스트를 빠르게 연사할 수 있습니다. 그녀의 특수 공격은 자신과 근처 팀원의 이동 속도를 대폭 높여주는 오라를 만듭니다. 그녀가 그것을 활성화하면 전체 팀이 눈 깜짝할 사이에 목표물로 돌진하거나 나쁜 상황에서 탈출할 수 있습니다.",
  "가젯은 모든 매치에 추가적인 전략의 층을 더해줍니다. 각 브롤러는 게임이 시작되기 전 선택할 수 있는 두 개의 독특한 가젯을 가지고 있지만, 매치 당 세 번만 사용할 수 있습니다. 크로우의 느려지는 독소나 쉘리의 돌진처럼 완벽한 타이밍에 사용된 가젯은 결투의 결과를 완전히 바꿀 수 있습니다. 랭크를 올리기 위해서는 가젯을 언제 아껴두고 언제 사용할지 아는 것이 중요한 기술입니다.",
  "스퀴크는 러프스 대령이 만든 오로지 개 침으로만 이루어진 사랑스러운 외계인입니다. 그의 폭발성 액체 덩어리는 벽, 바닥, 심지어 적 브롤러에게도 달라붙습니다! 짧은 지연 후 만족스러운 '펑' 소리와 함께 폭발하여 엄청난 범위 피해를 줍니다. 그의 공격은 좁은 길목을 통제하고 적 팀을 흩어져 후퇴하도록 만드는 데 완벽합니다.",
  "스타 파워는 파워 레벨 9에 도달하면 브롤러의 진정한 잠재력을 잠금 해제합니다. 이 패시브 능력들은 브롤러의 플레이 방식을 근본적으로 바꿉니다. 예를 들어, 보의 독수리의 눈은 수풀 속을 두 배 더 멀리 볼 수 있게 해주어 교활한 암살자들을 완벽히 차단합니다. 올바른 맵에 맞는 스타 파워를 선택하는 것은 경쟁 매치의 승패를 좌우할 수 있는 결정입니다.",
  "브롤볼에서 조직적인 밀어붙이기에 맞서 골을 방어하는 것은 압도적인 느낌을 줄 수 있습니다. 적 팀이 벽을 허물고 공을 네트 바로 앞까지 몰고 온다면 빠르게 행동해야 합니다. 얼어붙는 눈보라 특수 공격을 가진 게일이나 가젯을 사용하는 진처럼 넉백 능력을 가진 브롤러들은 공을 든 상대를 밀어내어 게임을 구할 수 있기 때문에 엄청나게 가치 있습니다.",
  "메가 돼지는 플레이어들이 놀라운 보상을 얻기 위해 팀을 이루는 거대한 클럽 이벤트입니다. 무한 탄약, 엄청나게 빠른 브롤러, 또는 독이 있는 수풀로 가득 찬 맵과 같은 미친 모디파이어가 있는 특별한 매치를 플레이해야 합니다. 이 매치에서 이기면 거대한 돼지를 부수는 데 기여하게 됩니다. 이벤트가 끝나면 돼지가 깨지며 모든 클럽원들에게 스타 드롭, 코인, 그리고 블링을 쏟아냅니다!",
  "자넷은 전투 중에 문자 그대로 하늘로 날아오르는 스턴트 조종사입니다. 특수 공격을 사용하면 제트팩을 활성화하여 벽, 물, 그리고 적의 공격을 넘어 날아갈 수 있으며, 공중에 있는 동안에는 완전히 무적 상태가 됩니다. 날아다니면서 아래에 있는 적들에게 로켓을 떨어뜨리는데, 자리를 지키려 할 때 대처하기 가장 짜증나는 브롤러 중 한 명입니다.",
  "맵 메이커 기능은 플레이어들이 창의력을 발휘하여 자신들만의 기발한 경기장을 디자인할 수 있게 해줍니다. 어떤 맵들은 경쟁 플레이를 위해 복잡하게 균형이 맞춰져 있는 반면, 다른 맵들은 수십 개의 점프 패드와 텔레포터로 가득 찬 완전한 혼돈 그 자체입니다. 매일 커뮤니티는 최고의 유저 제작 맵에 투표하며, 우승작은 모든 사람이 플레이하고 즐길 수 있도록 메인 게임에 추천됩니다.",
  "다이너마이크나 그롬 같은 스로어 캐릭터를 플레이하려면 항상 벽을 방패로 사용해야 합니다. 이들의 공격은 장애물을 넘어갈 수 있기 때문에 엄폐물이 많은 맵에서 활약합니다. 하지만 근접전에서는 엄청나게 취약합니다. 만약 에드가 같은 암살자가 벽을 넘어 스로어 바로 옆에 붙는다면 보통 몇 초 안에 게임이 끝납니다.",
  "5대5 게임 모드의 혼란스러운 성격은 전통적인 전략을 완전히 뒤집어 놓습니다. 열 명의 플레이어가 공격, 특수 공격, 가젯을 한꺼번에 마구 쏘아대면 화면은 눈부신 색상과 음향 효과의 폭발로 변합니다. 한쪽 맵에서 5명이 엄청나게 밀어붙이는 압도적인 상황에 팀이 밀리지 않도록 여러 가지 목표를 동시에 추적해야 합니다.",
  "타워 디펜스 시뮬레이터는 전략과 배치가 모든 것을 의미하는 게임입니다. 좀비의 초기 공세를 막기 위해 기본 스카우트와 스나이퍼로 시작합니다. 돈을 벌면 미니거너, 커맨더, 액셀러레이터와 같은 엄청나게 강력한 유닛을 배치할 수 있습니다. 거대한 보스를 상대로 마지막 공세에서 살아남으려면 팀과의 완벽한 조화와 타워를 최고 레벨로 업그레이드하는 것이 필요합니다.",
  "블록스버그에 오신 것을 환영합니다는 로블록스 최고의 삶 시뮬레이션 게임입니다. 대부분의 게임과 달리 오토바이로 피자를 배달하든 미용실에서 머리를 자르든 돈을 벌기 위해 실제로 직업을 가져야 합니다. 힘들게 번 돈으로 건축 모드에 들어가 자신이 꿈꾸는 집을 처음부터 디자인하고, 가구, 벽지, 조명 기구 하나하나를 직접 고를 수 있습니다.",
  "머더 미스터리 2에서 매 라운드는 엄청난 편집증으로 시작됩니다. 무고한 플레이어들은 누가 몰래 살인자인지 알아내려고 노력하면서 코인을 모으며 숨어다녀야 합니다. 보안관은 총을 가진 유일한 플레이어이며, 그들의 임무는 너무 늦기 전에 살인자를 쏘는 것입니다. 하지만 보안관이 실수로 무고한 사람을 쏘면 즉시 탈락하게 됩니다!",
  "입양하세요는 단순히 펫에 관한 게임이 아닙니다. 그것은 완전한 가상 경제입니다. 펫의 가치는 수요와 희귀성에 따라 끊임없이 변동합니다. 오래된 한정판 알에서 나온 펫이 갑자기 매우 귀중해져 마을 광장에서 거대한 거래 전쟁을 일으킬 수도 있습니다. 플레이어들은 꿈의 인벤토리에 한 걸음 더 다가가기 위해 거래에서 성공하기를 바라며 몇 시간이고 협상합니다.",
  "로블록스 스튜디오에서 자신만의 게임을 개발하는 것은 배우기는 놀라울 정도로 쉽지만 마스터하기는 엄청나게 어렵습니다. 기본 블록과 원기둥을 사용하여 맵을 만들고, 루아로 스크립트를 작성하여 게임이 실제로 작동하도록 할 수 있습니다. 수백만 명의 플레이어들이 그들의 기발한 상상력을 거대한 롤플레잉 도시부터 강렬한 1인칭 슈팅 게임까지 모든 것을 만들어내며 완벽하게 플레이할 수 있는 게임으로 바꾸어 놓았습니다.",
  "아스널은 빠른 전개, 혼란스러운 게임 플레이, 그리고 유쾌한 아나운서 목소리로 유명합니다. 무기를 선택할 수 없으며, 킬을 기록할 때마다 무기가 자동으로 바뀝니다. 연사되는 돌격소총에서 장전이 느린 머스킷이나 심지어 마법의 주문 책으로 교체하며 즉시 적응해야 합니다. 매치는 짧고 강렬하며 끊임없이 긴장하게 만듭니다.",
  "샤크바이트 같은 게임에서 스쿠버 다이빙을 하는 것은 끔찍한 경험입니다. 한 플레이어는 거대하고 굶주린 백상아리로 선택되고, 다른 모든 사람들은 무기로 무장한 배 위에서 스폰됩니다. 생존자들은 바다를 누비며 상어가 그들의 배를 완전히 파괴하기 전에 쏴야 합니다. 배가 침몰하면 살기 위해 넓은 바다를 헤엄쳐야만 합니다!",
  "더 헌트는 플레이어들이 숨겨진 배지를 모으기 위해 수십 개의 다양한 로블록스 게임을 가로질러 여행해야 했던 거대한 플랫폼 차원의 이벤트였습니다. 타이쿤 게임에서 특별한 오비를 완료하는 것부터 호러 게임에서 퍼즐을 푸는 것까지 챌린지들은 엄청나게 다양했습니다. 충분한 배지를 얻으면 헌신적인 배지 사냥꾼임을 증명하는 한정판 독점 아바타 액세서리를 잠금 해제할 수 있었습니다.",
  "피기는 깊은 세계관과 퍼즐 풀이 메커니즘으로 생존 호러 장르에 돌풍을 일으켰습니다. 당신은 소름 끼치는 맵에 갇혀 문을 열고 탈출하기 위해 색깔 있는 열쇠, 렌치, 톱니바퀴를 찾아야 합니다. 그러는 동안 내내 무시무시한 박쥐를 든 생물체가 천천히 당신을 쫓아옵니다. 맵의 구조를 파악하고 괴물보다 영리하게 대처하는 것만이 살아남는 유일한 방법입니다."
];

export function getRandomText(type, language = 'en') {
  const isKor = language === 'ko';
  let pool;
  if (type === 'paragraph') {
    pool = isKor ? KOR_PARAGRAPHS : EN_PARAGRAPHS;
  } else {
    pool = isKor ? KOR_SENTENCES : EN_SENTENCES;
  }
  const index = Math.floor(Math.random() * pool.length);
  return pool[index];
}

